### ISSUE TITLE
Understanding basic incubator design

### ISSUE THREAD

**Issue by doramelindatunde** [kivancsikert/ugly-duckling#19]
The central X can hold 200ml water, which evaporates in about a day and keeps humidity between 40-50%. (Good for most of the incubation period.) However, lifting the whole internal construct every day is not practical, it would be great if adding water could be done externally, into a transparent pipeline e.g. 

Each small V holds an extra 150 ml water and adds +5% humidity.

**Comment by lptr** [comment]
We now understand this design. It's not a very good one, especially because water cannot be loaded without opening the incubator up. It's also not a good system to automate.
