### ISSUE TITLE
Bad water-measurement

### ISSUE THREAD

**Issue by doramelindatunde** [kivancsikert/ugly-duckling#26]
Mains should only be used to measure drip-losses in Grafana, otherwise we get duplicated data.
Thus, the measurements of all boxes after mains should be subtracted. We should keep in mind that linearly timed watering will allow much fewer measurement points (mains, drains, animals) while still giving good water/bed data.

**Comment by lptr** [comment]
Do we want to do something here still?

**Comment by doramelindatunde** [comment]
ok

**Comment by lptr** [comment]
I've started measuring the different kinds of water flow meters. They have quite different characteristics based on the amount of flow.

Measurements:

https://docs.google.com/spreadsheets/d/1AdiQDayEqgdzuvxyAnY5iqzs-Qx-oSkFT-AGj4IGXWo/edit
